Repository babel-plugin-ember-test-metadata/babel-plugin-ember-test-metadata, pull requests merged in 2021-09, with the labels that each got.

#29 Support embroider file path references
  __tests__/__fixtures__/temp-test-123/embroider/123456/pathtest/embroider-prefix-test.js
  __tests__/__snapshots__/index-test.js.snap
  __tests__/index-test.js
  __tests__/utils-test.js
  src/index.js
  src/utils.js
Labels: enhancement

#33 Converting to monorepo
  .eslintignore
  .eslintrc.js
  .prettierrc.js
  README.md
  package.json
  packages/babel-plugin-ember-test-metadata/.babelrc
  packages/babel-plugin-ember-test-metadata/README.md
  packages/babel-plugin-ember-test-metadata/__tests__/__fixtures__/temp-test-123/embroider/123456/pathtest/embroider-prefix-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/__fixtures__/with-get-test-metadata-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/__fixtures__/with-hooks-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/__fixtures__/with-multiple-modules-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/__fixtures__/with-no-module-callback-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/__fixtures__/without-hooks-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/__snapshots__/index-test.js.snap
  packages/babel-plugin-ember-test-metadata/__tests__/index-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/utils-test.js
  packages/babel-plugin-ember-test-metadata/package.json
  packages/babel-plugin-ember-test-metadata/src/index.js
  packages/babel-plugin-ember-test-metadata/src/utils.js
  yarn.lock
Labels: internal

#34 Adding app template to test plugin with ember applications
  .gitignore
  packages/app-template/.editorconfig
  packages/app-template/.ember-cli
  packages/app-template/.eslintignore
  packages/app-template/.eslintrc.js
  packages/app-template/.gitignore
  packages/app-template/.prettierignore
  packages/app-template/.prettierrc.js
  packages/app-template/.template-lintrc.js
  packages/app-template/.travis.yml
  packages/app-template/.watchmanconfig
  packages/app-template/README.md
  packages/app-template/app/app.js
  packages/app-template/app/components/.gitkeep
  packages/app-template/app/controllers/.gitkeep
  packages/app-template/app/helpers/.gitkeep
  packages/app-template/app/index.html
  packages/app-template/app/models/.gitkeep
  packages/app-template/app/router.js
  packages/app-template/app/routes/.gitkeep
  packages/app-template/app/styles/app.css
  packages/app-template/app/templates/application.hbs
  packages/app-template/config/ember-cli-update.json
  packages/app-template/config/environment.js
  packages/app-template/config/optional-features.json
  packages/app-template/config/targets.js
  packages/app-template/ember-cli-build.js
  packages/app-template/package.json
  packages/app-template/public/robots.txt
  packages/app-template/testem.js
  packages/app-template/tests/helpers/.gitkeep
  packages/app-template/tests/index.html
  packages/app-template/tests/integration/.gitkeep
  packages/app-template/tests/test-helper.js
  packages/app-template/tests/unit/.gitkeep
  packages/app-template/vendor/.gitkeep
  yarn.lock
Labels: internal

#35 Adding test-scenarios package for acceptance-style tests
  .eslintrc.js
  .github/workflows/ci-build.yml
  package.json
  packages/app-template/app/app.js
  packages/app-template/app/index.html
  packages/app-template/app/router.js
  packages/app-template/config/environment.js
  packages/app-template/package.json
  packages/app-template/tests/index.html
  packages/app-template/tests/test-helper.js
  packages/babel-plugin-ember-test-metadata/package.json
  packages/test-scenarios/__tests__/scenario-test.js
  packages/test-scenarios/package.json
  yarn.lock
Labels: internal

#36 Removes unnecessary babel transpilation
  .github/workflows/ci-build.yml
  packages/babel-plugin-ember-test-metadata/.babelrc
  packages/babel-plugin-ember-test-metadata/__tests__/index-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/utils-test.js
  packages/babel-plugin-ember-test-metadata/index.js
  packages/babel-plugin-ember-test-metadata/package.json
  packages/babel-plugin-ember-test-metadata/utils.js
  yarn.lock
Labels: internal

#38 Add in repo test scenarios
  packages/test-scenarios/__tests__/__fixtures__/with-hooks-test.js
  packages/test-scenarios/__tests__/__fixtures__/with-multiple-modules-test.js
  packages/test-scenarios/__tests__/__fixtures__/without-hooks-test.js
  packages/test-scenarios/__tests__/scenario-test.js
  packages/test-scenarios/package.json
  yarn.lock
Labels: internal

#42 Add util test cases for different path scenarios
  packages/babel-plugin-ember-test-metadata/__tests__/__fixtures__/temp-test-123/embroider/123456/tests/embroider-prefix-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/__snapshots__/index-test.js.snap
  packages/babel-plugin-ember-test-metadata/__tests__/get-relative-paths-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/index-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/utils-test.js
  packages/babel-plugin-ember-test-metadata/get-relative-paths.js
  packages/babel-plugin-ember-test-metadata/utils.js
  packages/test-scenarios/__tests__/__fixtures__/with-hooks-assert-includes-test.js
  packages/test-scenarios/__tests__/__fixtures__/with-multiple-modules-assert-includes-test.js
  packages/test-scenarios/__tests__/__fixtures__/without-hooks-assert-includes-test.js
  packages/test-scenarios/__tests__/scenario-test.js
  packages/test-scenarios/package.json
  yarn.lock
Labels: enhancement

#43 Removes custom object path util in favor of object-path
  packages/babel-plugin-ember-test-metadata/__tests__/utils-test.js
  packages/babel-plugin-ember-test-metadata/index.js
  packages/babel-plugin-ember-test-metadata/package.json
  packages/babel-plugin-ember-test-metadata/utils.js
  yarn.lock
Labels: internal

#44 Adds config for package name and if running under embroider
  README.md
  packages/babel-plugin-ember-test-metadata/README.md
  packages/babel-plugin-ember-test-metadata/__tests__/index-test.js
  packages/babel-plugin-ember-test-metadata/__tests__/utils-test.js
  packages/babel-plugin-ember-test-metadata/index.js
  packages/babel-plugin-ember-test-metadata/utils.js
  packages/test-scenarios/__tests__/scenario-test.js
Labels: breaking
